name: build and push images

on:
  push:
    branches: ['main']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - { postgres: 14, alpine: '3.17' }
          - { postgres: 14, alpine: '3.18' }
          - { postgres: 15, alpine: '3.17' }
          - { postgres: 15, alpine: '3.18' }
          - { postgres: 16, alpine: '3.17' }
          - { postgres: 16, alpine: '3.18' }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ricardobchaves6/postgres-backup-gcp-storage:postgres${{ matrix.postgres }}-alpine${{ matrix.alpine }}
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine }}
            POSTGRES_VERSION=${{ matrix.postgres }}
          platforms: |
            linux/amd64
            linux/arm64